const dummy = [
  {
    id: 1,
    name: 'dummy1',
    description: 'dummy1 description',
    price: 100,
    image: 'https://picsum.photos/200/300',
    reserve: false,
  },
  {
    id: 2,
    name: 'dummy2',
    description: 'dummy2 description',
    price: 200,
    image: 'https://picsum.photos/200/300',
    reserve: false,
  },
  {
    id: 3,
    name: 'dummy3',
    description: 'dummy3 description',
    price: 300,
    image: 'https://picsum.photos/200/300',
    reserve: false,
  },
  {
    id: 4,
    name: 'dummy4',
    description: 'dummy4 description',
    price: 400,
    image: 'https://picsum.photos/200/300',
    reserve: false,
  },
  {
    id: 5,
    name: 'dummy5',
    description: 'dummy5 description',
    price: 500,
    image: 'https://picsum.photos/200/300',
    reserve: false,
  },
  {
    id: 6,
    name: 'dummy6',
    description: 'dummy6 description',
    price: 600,
    image: 'https://picsum.photos/200/300',
    reserve: false,
  },
  {
    id: 7,
    name: 'dummy7',
    description: 'dummy7 description',
    price: 700,
    image: 'https://picsum.photos/200/300',
    reserve: false,
  },
];

export default dummy;
